language: node_js
node_js:
  - lts/*
if: tag IS blank
jobs:
  include:
    - os: windows
      env:
        - YARN_GPG=no
    - os: osx
      osx_image: xcode10.2
    - os: linux
      dist: xenial
script:
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then yarn release; else yarn build; fi
