language: node_js
node_js:
  - lts/*
os:
  - windows
    env: YARN_GPG=no
  - osx
  - linux
script:
  - yarn build
    if: NOT branch = master OR NOT type = push
  - yarn release
    if: branch = master AND type = push
