language: node_js
node_js:
  - lts/*
script: yarn build
deploy: yarn release
jobs:
  include:
    - os: windows
      env: YARN_GPG=no
    - os: osx
    - os: linux
stages:
  - name: script
    if: NOT branch = master OR NOT type = push
  - name: deploy
    if: branch = master AND type = push
