name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-10.15
          - ubuntu-16.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build app
      if: github.ref != 'refs/heads/master'
      run: yarn build
    - name: Publish app
      if: github.ref == 'refs/heads/master'
      run: yarn release
